apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-postgres
  namespace: store-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-postgres
  template:
    metadata:
      labels:
        app: notification-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: notification-db-config
            - secretRef:
                name: notification-postgres-secret
          volumeMounts:
            - name: notification-postgres-storage
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "notification_admin", "-d", "notification_db"]
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: notification-postgres-storage
          persistentVolumeClaim:
            claimName: notification-postgres-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notification-postgres-pvc
  namespace: store-crm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi